---
substitutions:
  friendly_name: WROVER_DevKit

esphome:
  name: wrover_devkit
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

esp32_ble_tracker:

# Enable Home Assistant API
<<: !include include_api.yaml
<<: !include include_ota.yaml
<<: !include include_wifi.yaml
<<: !include include_mqtt.yaml
<<: !include include_sensor.yaml
<<: !include include_sensor.yaml
<<: !include include_switch.yaml

<<: !include include_standart_mesh.yaml

# Buttons
binary_sensor:
  - <<: !include {
      file: include_button.yaml,
      vars: { id: BtnA, gpio: GPIO39 },
    }
  - <<: !include { file: include_binary_sensor.yaml }

#i2c:
#  sda: 21
#  scl: 22
#  scan: false # nothing to scan
#  id: bus_a

spi:
  miso_pin: GPIO12
  clk_pin: GPIO13
  mosi_pin: GPIO11

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO15
    num_leds: 1
    rmt_channel: 1
    chipset: SK6812
    name: ${friendly_name} LED Light
    restore_mode: ALWAYS_OFF
    id: side_light
    default_transition_length: 0s
#captive_portal:
