---
binary_sensor:
  - platform: template
    id: 'dim_display_on'
    filters:
      - delayed_off: 1min # Dim display
    on_press: # brightness is float (from 0 to 1). 1 = 100%
      then:
        if:
          condition:
            light.is_off: '${display_backlight}'
          then:
            - logger.log: 'Display on!'
            - light.turn_on:
                id: '${display_backlight}'
                brightness: 0.5
                transition_length: 1s

    on_release: # brightness is float (from 0 to 1). 0.01 = 1%
      then:
        - logger.log: 'Display half dimmed'
        - light.turn_on:
            id: '${display_backlight}'
            brightness: 0.01
            transition_length: 2s

  - platform: template
    id: 'dim_display_off'
    filters:
      - delayed_off: 2min # Turn off the display
    on_release:
      then:
        - logger.log: 'Display OFF!'
        - light.turn_off:
            id: '${display_backlight}'
            transition_length: 2s
