---
# CO₂ and Volatile Organic Compound Sensor
sensor:
  - platform: sgp30
    i2c_id: bus_a
    eco2:
      name: "${friendly_name} eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "${friendly_name} TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 1s
    # baseline
    #  ecov2_baseline: 0x8E9F
    #  tvoc_baseline: 0x8E9F
    compensation:
      temperature_source: temperature_sensor
      humidity_source: humidity_sensor