---
# Temperature + Humidity Sensor
sensor:
  - platform: sht3xd
    i2c_id: bus_a
    temperature:
      name: '${friendly_name} Temperature (from not correct sensor)'
      id: not_correct_temperature_sensor
      accuracy_decimals: 2
    humidity:
      name: '${friendly_name} Humidity'
      id: humidity_sensor
      accuracy_decimals: 2
    address: 0x44
    update_interval: 60s
    # By-default, it is OFF
    heater_enabled: true
