---
sensor:
  - platform: sht4x
    i2c_id: bus_a
    address: 0x44
    update_interval: 60s
    precision: High
    heater_max_duty: 0.05
    temperature:
      name: '${friendly_name} Temperature (from not correct sensor)'
      id: not_correct_temperature_sensor
      accuracy_decimals: 1
    humidity:
      name: '${friendly_name} Humidity'
      id: humidity_sensor
      accuracy_decimals: 1
