---
name: Build
run-name: "Build [${{ github.ref_name }}](${{ github.event_name }}) by ${{ github.actor }}"

on:
  push:
    branches:
      - master
      - cicd
    paths:
      - '*.yaml'
      - '*.yml'
      - '.github/workflows/build.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    name: "Build ${{ matrix.yaml-file }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yaml-file:
          - m5atom-s3.yaml
          - m5stack-core2.yaml
          - m5timer-cam.yaml
          - m5stick-plus.yaml
          - esp32cam.yaml
    env:
      VERSION: ''
      TZ: 'Asia/Baku'
      YAML: |
        ${{ secrets.SECRETS_YAML }}
    outputs:
      VERSION: ${{ steps.step-output.outputs.version }}
      FIRMWARE_NAME: ${{ steps.step-output.outputs.firmware_name }}
      SHA: ${{ steps.step-output.outputs.sha }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create secrets.yaml"
        run: |
          VERSION=dev-$(date +'%Y%m%d-%H%M')-${{ github.run_attempt }}
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "${{ env.YAML }}"  > ./secrets.yaml

      - name: "Run action"
        uses: esphome/build-action@v5.0.0
        id: esphome-build
        with:
          yaml-file: ${{ matrix.yaml-file }}
          version: dev
          platform: linux/amd64
          cache: true
          release-summary: ''
          release-url: "https://github.com/derskythe/esphome-playground"
          complete-manifest: true

      - name: "Write version to file"
        run: echo ${{ steps.esphome-build.outputs.version }} > ${{ steps.esphome-build.outputs.name }}/version

      - name: "Upload ESPHome binary"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.esphome-build.outputs.name }}-${{ env.VERSION }}
          path: ${{ steps.esphome-build.outputs.name }}

      - name: "Output Values"
        id: step-output
        run: |
          echo "VERSION=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
          echo "FIRMWARE_NAME=${{ steps.esphome-build.outputs.name }}" >> "$GITHUB_OUTPUT"
          echo "SHA=$(git rev-parse --verify HEAD)" >> "$GITHUB_OUTPUT"

  verify:
    name: "Verify ${{ matrix.yaml-file }}"
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        yaml-file:
          - m5atom-s3.yaml
          - m5stack-core2.yaml
          - m5timer-cam.yaml
          - m5stick-plus.yaml
          - esp32cam.yaml
    env:
      VERSION: ${{ needs.build.outputs.version }}
      FIRMWARE_NAME: ${{ needs.build.outputs.firmware_name }}
      SHA: ${{ needs.build.outputs.sha }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Download files"
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.FIRMWARE_NAME }}-${{ env.VERSION }}

      - name: "List files"
        run: |-
          ls -al
          tree

      - name: "[ALL] Create or update RELEASE ${{ env.VERSION }} with assets 🌟"
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ./.github/create-or-update-release.ps1 ./ "${{ env.FIRMWARE_NAME }}" "${{ env.VERSION }}" ${{ github.repository }} ${{ github.ref_name }} ${{ env.SHA }}
